In [1]:
import numpy as np 

In [3]:
list_a = [1,2,3,4,5,6]
list_a = [[1,2,3], [4,5,6]]
len(list_a)

2

In [6]:
array_a = np.array(list_a)

In [4]:
type(list_a)

list

In [7]:
type(array_a)

numpy.ndarray

In [8]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [9]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [10]:
array_a.shape 

(2, 3)

In [19]:
# list_a.shape 
len(list_a)
#list_a has 3 elements per list 
len(list_a[0])
len(list_a[1])

3

In [21]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [22]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [24]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [25]:
print(list_b )

[1, 2, 3, 4, 5, 6]


In [26]:
print(array_b)

[5 7 9]


In [27]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])