In [3]:
import numpy as np 

Indexing


In [3]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

Specific Values 



In [5]:
#Each row is known as elements
array_a[0]
array_a[1]

array([4, 5, 6])

In [8]:
#Getting specific values from the array 
array_a[0][0]
array_a[1][0]

4

In [9]:
#Alternative method 
array_a[1,0]

4

In [10]:
array_a[:,0]

array([1, 4])

Negative Indices

In [11]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [12]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array_a[-1]

array([1, 2, 3])

In [15]:
array_a[:,-1]

array([3, 6])

Assigning Values

In [4]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#Changing a specific value
array_a[0,2] = 9 
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [18]:
#Changing a specific row 
array_a[0] = 9 
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [5]:
#Changing the first row 
array_a[:,0] = 9 
array_a


array([[9, 2, 3],
       [9, 5, 6]])

In [20]:
list_a = [8,7,8]
array_a[0] = list_a 
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [21]:
#Assigning same values to all the rows 
array_a[:] = 9 
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [22]:
#Overwrite the array completely 
array_a = 9 
array_a

9

In [23]:
type(array_a)

int

Elementwise Properties

In [24]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [25]:
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
array_a + 2

array([ 9, 10, 11])

In [28]:
array_b + 2
array_b * 2 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [29]:
#The shapes of the array need to be compatible
array_a + array_b[0]

array([ 8, 10, 12])

In [31]:
array_a + array_b[1]
array_a * array_b[1]

array([28, 40, 54])

In [32]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [33]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

In [34]:
array_a - array_b

array([[6, 6, 6],
       [3, 3, 3]])

In [35]:
array_b - array_a

array([[-6, -6, -6],
       [-3, -3, -3]])

Types of Data Supported by Numpy