In [1]:
import numpy as np 

In [2]:
# Arrays 
#1-d array 
array_a = np.array([1,2,3])
array_a 

array([1, 2, 3])

In [3]:
#2-d array 
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_c = np.array([[1,2,3], [4,5,6],
[7,8,9]])
array_c


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#N-d arrays
#nd array = n-dimensional array
array_a = np.array([1,2,3])
array_a  

[1 2 3]


(3,)

In [12]:
print(array_a)
type(array_a)

[1 2 3]


numpy.ndarray

In [13]:
#A 1-D array of size 3 
array_a.shape

(3,)

In [ ]:
#2-D array 
array_b = np.array([[7,8,9], [10,11,12]])


In [14]:
type(array_b)

numpy.ndarray

In [15]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [20]:
#Array contains 2 one-dimensional array of 
#size 3
array_b.shape 
#2-d array is like an matrix 
array_b.shape[0]
array_b.shape[1]

3

In [21]:
array_c = np.array(13)
type(array_c)

numpy.ndarray

In [22]:
print(array_c)


13


In [23]:
array_c.shape 

()

In [26]:
array_d = np.array([15])
type(array_d)
print(array_d)
array_d.shape #A 1-D array of size 3 
array_a.shape


[15]


(1,)