Working with arrays

In [1]:
import numpy as np 

Slicing

In [2]:
matrix_a = np.array([[1,2,3], [4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

Basic Slicing

In [3]:
#Creating an new array by taking chunks of values out of an existing one 
#The slices consist of adjacent pieces of data(two consecutive columns or 3 consecutive rows)
#It can contain entire rows and columns of the original array or just parts of them 
#Indexing in numpy is closed open ( [0:1) ) we don't include the upper limit 

In [13]:
matrix_a[0:1]
# matrix_a[0:2]

array([[1, 2, 3]])

In [23]:
matrix_a[:1]
matrix_a[2:]
matrix_a[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#matrix_a[n:] and matrix_a[:n] are complementary slices
#indexing is specific indexing 
#Slicing is interval slicing 

In [17]:
#Indexing
matrix_a[1]

array([4, 5, 6])

In [20]:
#Slicing
matrix_a[:-1]
#Indexing
matrix_a[-1]

array([4, 5, 6])

In [21]:
#Slicing columns 
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [24]:
#How to slice rows and columns both simulatneosuly
matrix_a[1:,1:]

array([[5, 6]])

Stepwise Slicing 

In [ ]:
# A type of slicing where we don't take consecutive values 
# Values which are a certain distance apart 
# By default step is equal to 1 
# The Step part of slicing works identical for each dimension

In [25]:
matrix_b = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_b 

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [26]:
matrix_b[:,:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [27]:
matrix_b[::, ::]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [28]:
matrix_b[::2, ::]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [29]:
matrix_b[::, ::2]

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [30]:
matrix_b[::2, ::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [31]:
#Negative stepwise slicing 
matrix_b[::-2, ::2]

array([[4, 3, 0],
       [1, 1, 0]])

In [32]:
matrix_b[-1::-1, ::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

Conditional Slicing

In [34]:
matrix_c = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_c 

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [35]:
matrix_c[:,0]

array([1, 3, 4])

In [36]:
matrix_c[:,0] > 2

array([False,  True,  True])

In [37]:
matrix_c[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [38]:
#What if we wanted to know the exact values which satisfy this condition ? 
#Write the conditional part as the index 
matrix_c[matrix_c[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [39]:
matrix_c[matrix_c[:,:] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [40]:
#& -and operator
matrix_c[(matrix_c[:,:] % 2 == 0) & (matrix_c[:,:] <= 4)]

array([2, 0, 4, 4, 0])

In [43]:
# | or operator 
matrix_c[(matrix_c[:,:] % 2 == 0) | (matrix_c[:,:] <= 4)] 

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

Dimensions and the Squeeze Function

In [44]:
matrix_d = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_d 

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [45]:
type(matrix_d[0,0])

numpy.int64

In [46]:
type(matrix_d[0,0:1])

numpy.ndarray

In [47]:
print(matrix_d[0,0:1])

[1]


In [48]:
type(matrix_d[0:1, 0:1])

numpy.ndarray

In [49]:
print(matrix_d[0:1, 0:1])

[[1]]


In [52]:
#Scalar
print(matrix_d[0,0].shape)
#Vector
print(matrix_d[0,0:1].shape)
#Matrix
print(matrix_d[0:1, 0:1].shape)

()
(1,)
(1, 1)


In [ ]:
#The squeeze method 
#Removes all the unnecessary dimensions of an array 
#always return N-d arrays 

In [53]:
matrix_d[0:1, 0:1].squeeze()

array(1)

In [54]:
type(matrix_d[0:1, 0:1].squeeze())

numpy.ndarray

In [55]:
matrix_d[0:1, 0:1].squeeze().shape

()

In [56]:
print(matrix_d[0:1, 0:1].squeeze())

1


In [57]:
#alternative syntax 
np.squeeze(matrix_d[0:1, 0:1])

array(1)

In [58]:
#Scalar
print(matrix_d[0,0].squeeze().shape)
#Vector
print(matrix_d[0,0:1].squeeze().shape)
#Matrix
print(matrix_d[0:1, 0:1].squeeze().shape)

()
()
()
